### PR TITLE
Fixes #64 Set sensitivity of uploaded content when always show spoile…

### LINKED ISSUE #64: Users with "Always Show CW Field" option enabled cannot control whether or not their images are marked as sensitive.
### Expected behavior
When a user has the "**Always Show CW Field**" option enabled should be able to control whether or not the images they post are marked as sensitive or not. So, if a user with that option enabled wants to post an image without marking it as sensitive, they should be able to deselect the checkbox that marks the image as sensitive before they post it. 

### Actual behavior

Users with the "**Always Show CW Field**" option are unable to deselect the checkbox to mark the image as not sensitive. This forces them to always post images as sensitive, regardless if that was their intent or not.

### Steps to reproduce the problem

1) Either Create a New Account or go into the preferences page and enable the option to "**Always Show CW Field**" under the "**Mods**" section.

### Specifications
I found this issue in the staging version of BeachCity, which was "beachcity1.7.0".

I tested this issue on both Google Chrome (on a Windows 10 Pro install with most recent updates) and on an Ubuntu 18.04 VM with Firefox 67.0.

### PR DESCRIPTION
**Pull request by robinmaypanpan**
…r is true.

### CODE REVIEW

File: app/javascript/mastodon/reducers/compose.js [hunk 1]
```diff
@@ -128,7 +128,9 @@ function appendMedia(state, media) {
     map.set('resetFileKey', Math.floor((Math.random() * 0x10000)));
     map.set('idempotencyKey', uuid());
 
-    if (prevSize === 0 && (state.get('default_sensitive') || state.get('spoiler'))) {
+    const isSpoilerActive = enableAlwaysShowSpoiler ? state.get('spoiler_text').length > 0 : state.get('spoiler');
```
Comment (aarchiba) [inline app/javascript/mastodon/reducers/compose.js:131]: This creates a distinction between auto-CW and manual CW: manual CW with an empty field can't have insensitive media. Is this distinction likely to cause programming bugs down the road? Is it likely to confuse users? Would it be better to just have `state.get('spoiler_text').length > 0` be the sole criterion for whether media can be insensitive? The downside from a user's point of view is that their media only gets turned sensitive after they start typing.

File: app/javascript/mastodon/reducers/compose.js [hunk 2]
```diff
@@ -221,7 +223,8 @@ export default function compose(state = initialState, action) {
       .set('is_composing', false);
   case COMPOSE_SENSITIVITY_CHANGE:
     return state.withMutations(map => {
-      if (!state.get('spoiler')) {
+      const isSpoilerActive = enableAlwaysShowSpoiler ? state.get('spoiler_text').length > 0 : state.get('spoiler');
+      if (!isSpoilerActive) {
```
Comment (aarchiba) [inline app/javascript/mastodon/reducers/compose.js:227]: I don't know how tooltips work but would it make sense to have one active so that the user gets some explanation when they click on the check box and nothing happens?

File: app/javascript/mastodon/reducers/compose.js [hunk 3]
```diff
@@ -238,9 +241,13 @@ export default function compose(state = initialState, action) {
       }
```
Comment (aarchiba) [inline app/javascript/mastodon/reducers/compose.js:241]: This if statement fires when turning spoilerness off. It's not a problem, because the media will already be marked sensitive, but it strikes me as a confusing situation lying in wait. Branching based on whether turning spoilerness on or off would also be a natural place to introduce an assertion, if those can be made to do something useful when they fail: when turning spoilerness off, assert that the media *was* marked sensitive.

**Review by aarchiba — APPROVED** [review]
I don't know whether assertions can be made to do something useful but it would seem like a good idea to check the invariant "non-empty CW text implies media marked sensitive" from time to time as we seem to have quite a number of ways to change both aspects and it would be unpleasant to miss a corner case.

All this stuff is happening at the UI stage, but there is also a transformation that happens at transmission - a manually activated but empty CW box is turned into no CW, for example. Also, somewhat surprisingly, an empty body results in a CW being turned into the message body (any media remains marked sensitive). 

What happens to automatically attached previews? For example a YouTube link sometimes results in the thumbnail appearing in the message - is there a concern about this sort of thing getting appropriate sensitivity flagging? (Which I guess would be sensitive if and only if it were in the body of a CWed message?)

File: app/javascript/mastodon/reducers/compose.js (hunk 2 above)
Comment (robinmaypanpan) [reply app/javascript/mastodon/reducers/compose.js:227]: I like this idea.
